### ISSUE TITLE
Twat 

### ISSUE THREAD

**Issue by hxrry999** [approachcircle/approOS#1]
##

**Comment by approachcircle** [comment]
It isn't stealing code if the code is open-source, it's public and available for anyone to use. Think of this as a fork of the original code.

**Comment by hxrry999** [comment]
but init a bit of a bum face thing to not give him credit tho :(

**Comment by approachcircle** [comment]
no credit is required, MikeOS didn't specify that you need to credit him in any variations of his code. it would be like me writing `print("OS STARTED")` and expecting everyone to credit me when they type a print statement.
